### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/remote-settings-lambdas#252]
Not sure what the state of 3.7 support is inside the libraries we depend on. E.g. `kinto-signer`. 

Whatever we do, we must remember that we have 2 different Python environments. The one inside `Dockerfile` and the one inside the `.travis.yml` file.

**Comment by leplatrem** [comment]
python 3.7 should be our target, that's what we use in kinto-dist (where kinto-signer is used). 

However I don't know about AWS lambda. @autrilla any hint?

**Comment by autrilla** [comment]
Currently Lamda only supports up to 3.6 https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by peterbe** [comment]
I don't understand. What about this:

<img width="762" alt="Screen Shot 2019-03-13 at 8 31 36 AM" src="https://user-images.githubusercontent.com/26739/54279082-8adb7980-456a-11e9-9058-f30bef7f69b5.png">

**Comment by autrilla** [comment]
I misread, you're right. We can use 3.7 with no issue.

**Comment by peterbe** [comment]
I see now that they way they sorted that table, it totally looks like 3.6 is the highest version and 2.7 the lowest. Silly of them.

**Comment by peterbe** [comment]
Which one should you use [python3.7-slim](https://github.com/docker-library/python/blob/9bb5d46dbcf16250a2d292ddc1e0b7a792aa275f/3.7/stretch/slim/Dockerfile) or [python3.7-alpine](https://github.com/docker-library/python/blob/9bb5d46dbcf16250a2d292ddc1e0b7a792aa275f/3.7/alpine3.9/Dockerfile)? I never know. 

According to [this blog post](https://blog.realkinetic.com/building-minimal-docker-containers-for-python-applications-37d0272c52f3) the difference between `python3.7` and `python3.7-alpine` is 714MB vs 115MB respectively. But it doesn't mention `python3.7-slim`. 

According to [this blog post](https://snarky.ca/what-are-the-popular-docker-images-for-python/) the Alpine one is, by 54% share, the most popular Python docker image. 

Does it matter? Possibly not much because we only use Docker to generate the .zip which is uploaded it AWS Lambda. But perhaps when we move to GCP it starts to matter since we'd run the docker containers as serverless components. Right?

In the grand scheme of things, it probably doesn't matter much, but it'd be interesting to take this opportunity to learn for when it does matter.

**Comment by autrilla** [comment]
I don't think it matters right now for Lambda, but as you mention it will matter on GCP. I think alpine images weren't great security wise, at least in the past, so we lean towards not using those. I don't see a reason not to use `-slim` though.

**Comment by peterbe** [comment]
@mythmon Do you have any strong preferences or insights on the topic starting at comment: https://github.com/mozilla-services/remote-settings-lambdas/issues/252#issuecomment-472988663

**Comment by peterbe** [comment]
>  alpine images weren't great security wise

Seems like a big statement. Do you have any links to point to that?

**Comment by mythmon** [comment]
I don't have strong opinions, but I have some weak ones. I just checked, and Th sizes are as follows:

| Image | Size |
| :-- | --: |
| python:3.7 | 929MB |
| python:3.7-slim | 143MB |
| python:3.7-alpine | 86MB |

`-slim` gets away with this size by not including lots of things. I think that's fine, as it is pretty to add them back in with `apt-get`. I think using `-slim` is an easy win that we should do.

`-alpine` makes this even smaller mostly by switching out Debian for [Alpine Linux](https://www.alpinelinux.org/). There isn't anything wrong with Alpine that I know, but it has fewer users, fewer developers, and generally less attention. That means that any problems that exist (security or otherwise) will go unnoticed longer, and take longer to fix, on average.

I also don't know the Alpine userland very well. I feel much more comfortable in Debian. It has the tools I expect, and most resources online refer to Debian, not Alpine.

For both of these reasons, I think `python:3.7-slim` is the image we should use.

**Comment by autrilla** [comment]
> > alpine images weren't great security wise
> 
> Seems like a big statement. Do you have any links to point to that?

I was pointed to this: https://kubedex.com/follow-up-container-scanning-comparison/. Really, I have no idea what we should use, but if we want to use alpine I'd talk to secops beforehand.

**Comment by peterbe** [comment]
Our current Dockerfile contains: [`apt-get update && apt-get install -y zip`](https://github.com/mozilla-services/remote-settings-lambdas/blob/5bcd26b0dfefd7af8abf38d19e92f43268eb5986/Dockerfile#L2) which is another reason to not rock the Debian-boat.
